version: '3.7'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn app.wsgi:app
    expose:
      - 8000
    env_file:
      - ./.env
  ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: static_volume
        target: /usr/src/frontend/dist
  nginx:
    build: ./nginx
    volumes:
      - type: volume
        source: static_volume
        target: /dist
    ports:
      - 1337:80
    depends_on:
      - web
      - ui

volumes:
  static_volume:
