version: '3.7'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    command: gunicorn app.wsgi:app --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env
  ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - type: volume
        source: static_volume
        target: /usr/src/frontend/dist
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - type: volume
        source: static_volume
        target: /dist
    links:
      - "web"
    ports:
      - 8080:80
    depends_on:
      - web
      - ui

volumes:
  static_volume:
