name: Online Hat CI Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose
        run: docker-compose up --build -d
      - name: Check running containers
        run: docker ps -a
      - name: Run test suite
        run: |
          docker-compose exec web poetry run pytest
        env:
          COMPOSE_INTERACTIVE_NO_CLI: true
